### ISSUE TITLE
Hi i have some issue pls help me!

### ISSUE THREAD

**Issue by UKVATOP** [r3ge/KeydropAutocode#13]
C:\Users\UKVA3\Desktop\KeydropAutocode-main>node index.js
 Keydrop Autocode V4
 If you see this but the app keeps crashing, refresh your cookies and check if your token is valid.
 If the console dosent say account loaded it means your missing cookie file(s).
 Check out our github wiki for the FAQ
Account key-drop.com.cookies.json loaded
C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:129
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:129:26)
    at Client.login (C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\Client.js:254:21)
    at run (C:\Users\UKVA3\Desktop\KeydropAutocode-main\index.js:57:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

Node.js v18.16.0

**Comment by UKVATOP** [comment]
Keydrop Autocode V4
 If you see this but the app keeps crashing, refresh your cookies and check if your token is valid.
 If the console dosent say account loaded it means your missing cookie file(s).
 Check out our github wiki for the FAQ
Account key-drop.com.cookies.json loaded
C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:129
    const invalidToken = new Error(WSCodes[4004]);
                         ^

Error [TOKEN_INVALID]: An invalid token was provided.
    at WebSocketManager.connect (C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\websocket\WebSocketManager.js:129:26)
    at Client.login (C:\Users\UKVA3\Desktop\KeydropAutocode-main\node_modules\discord.js\src\client\Client.js:254:21)
    at run (C:\Users\UKVA3\Desktop\KeydropAutocode-main\index.js:57:9)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  [Symbol(code)]: 'TOKEN_INVALID'
}

Node.js v18.16.0

C:\Users\UKVA3\Deskt

**Comment by ulucyldz** [comment]
In order to get the TOKEN, go to https://www.base64decode.org/ then decode

T1RjMU16azVNemd3TXpRek5EWTRNRGswLkdmdGNDYS50VjFmOFpyeW8zQ0lLTWYwUmFyVWhWYWc4bVJTcjlWalJFMmNCSQ==

The decoded result is the token

Copy it, then go to config.js > discord token section > paste it 

and u will be fine

**Comment by xsergiuszx** [comment]
I got the same problem but the bot was working for few days. Now I got token error. How can I get a working token?

**Comment by ulucyldz** [comment]
Yeah, hours later same problem occurred to me too. I hope this will be fixed in the next patch.

**Comment by xsergiuszx** [comment]
I hope it'll be fixed soon :/ But there is still no replay from devs

**Comment by bijkomune** [comment]
Token still not working

**Comment by r3ge** [comment]
> I hope it'll be fixed soon :/ But there is still no replay from devs

There is info about it on the discord server.
